### ISSUE TITLE
Planning to buy a hot tub 

### ISSUE THREAD

**Issue by Jens-Wymeersch** [gazoodle/gecko-home-assistant#11]
Anything I need to ask specifically to the vendor in order for this to work ? Which types of Gecko equipment has this been tested on ? Would it be possible to share some views of the UI ?

**Comment by gazoodle** [comment]
Yes, you need to make sure your spa has a modern Gecko control module and you'll need to buy the [in.touch](https://geckointouch.com/) module to go with it.

**Comment by texbid** [comment]
Mine works with
Ye.5 control
In.k800 topside
In.touch 2 wifi module

**Comment by gazoodle** [comment]
Reopening as a memory jogger to add some sample UI shots to README.md

**Comment by Jens-Wymeersch** [comment]
@gazoodle Thank you for your quick reply.

**Comment by stevenfletcher125** [comment]
I am a new starter to HA so bear with me but I cannot seem to get this to manually install (no HACS) any tips?

**Comment by gazoodle** [comment]
Ooops, probably my fault for staging an unreleased version in the main branch. I expect this is because the requirements are for a version of geckolib that isn’t available on PyPi yet…

Anyway, if you modify the file `manifest.json` and change the requirements line to `    "geckolib>=0.3.23" ` this might help.

**Comment by gazoodle** [comment]
Actually, that won’t work because the staged version is expecting functionality in geckolib, so you’ll just get errors in the logs by making that change. Sorry, right now this isn’t going to work this way, in fact I’m not even sure it’ll work cleanly from HACS. Let me run some more tests and see if I can get this working for you.

**Comment by gazoodle** [comment]
Ok, @stevenfletcher125 try the download again please. I've released `geckolib v0.3.24` which has the eco switch functionality in the library and now the integration `v0.0.12` which has the requirement pinned to that version. 

I was planning on pinning the integration to a specific geckolib version since I know that the async work coming along may have compatibility issues that need managing carefully, so this is something that was needed anyway.

**Comment by stevenfletcher125** [comment]
Working superb now, your a star

**Comment by gazoodle** [comment]
Screenshot added to README.md
