### ISSUE TITLE
Error Cconditions

### ISSUE THREAD

**Issue by maegibbons** [gazoodle/gecko-home-assistant#18]
Hi

Firstly, this is a great integration.

I have it working with Home Assistant and it works very well.

I have a particular issue with my spa which generates a FLO error condition.

Where are you at the moment with detecting and monitoring Error conditions?

I would really like to get an alert on it in Home Assistant but assume there is work to do in geckolib to expose it?

Krs

Mark

**Comment by rct** [comment]
@maegibbons - when you had the FLO error condition, were you able to determine from GeckoShell whether there is already support in Geckolib for detecting errors from the controller?

In order to get an error entity or entities in Home Assistant that could be used for alerting/notifications, does work also need to be done in Geckolib, or just the Home Assistant custom component?

Also might help to change the issue title to something more specific like "Expose controller error conditions to Home Assistant"

**Comment by maegibbons** [comment]
From hours and hours of studying the code, the error conditions appear to be reported in the status block in the driver.

They need to be exposed in the integration but not got around to that yet.

**Comment by gazoodle** [comment]
I’m on it. Next thing to look at 😀

**Comment by gazoodle** [comment]
Fixed in v0.1.9
