### ISSUE TITLE
blower being turned on at cyclic times

### ISSUE THREAD

**Issue by stepir** [gazoodle/gecko-home-assistant#39]
starting with the latest HA version (running core-2021.12.8) I’ve noticed the blower being switch on and off on their own.

Every X hours the blowers turn on for exactly 1 min and then they turn off. As per the logger it’s not really an automation or a user command enabling (and disabling it):

![](https://community-assets.home-assistant.io/original/4X/7/3/9/7394c1db01436927c4361beecf179f351d6620a3.png)

while when I turn it on it is logged in this way

![](https://community-assets.home-assistant.io/original/4X/2/1/b/21b3f13af97d9b4e63be91465e30f0cd8a23c6d2.png)

Anyone seeing something similar?

**Comment by jasondefuria** [comment]
Has it been colder where you are? When it is colder, the circuit board turns the blower on for about a minute ever few hours to have it pass over the temperature sensor in the water to get a reading and determine whether heat needs to be applied.

**Comment by stepir** [comment]
> Has it been colder where you are? When it is colder, the circuit board turns the blower on for about a minute ever few hours to have it pass over the temperature sensor in the water to get a reading and determine whether heat needs to be applied.

it's a very good explanation and I think as well this might be somehow related - It's something that is not HA related then.

The thing that make me wonder is that the system was used last year in the same period - it was way much more colder than this year, and never happened before.... perhaps a firmware update bring this change?

**Comment by gazoodle** [comment]
@jasondefuria makes a good point, I think it's most likely down to your tub.

Thinking about it I think it might be the filter purge and clean cycle running. The episodic nature and the time that the blower runs for seems most likely. The 1 minute run is too coincidental to really be anything else, it's exactly the amount of time the spa pack will run blowers and pumps to purge the plumbing prior to starting a filter cycle!

There are a bunch of config options to control how frequently this occurs. 

Not sure why this might have changed recently, perhaps HA started recording changes when they come from the underlying system rather than being triggered by a HA user or automation?

Anyway, I'm pretty sure this isn't down to the integration or library, so I'll close this, but please reopen if you disagree or have more data.

Thanks
