### ISSUE TITLE
Change Celcius to fahrenheit

### ISSUE THREAD

**Issue by xKronyx** [gazoodle/gecko-home-assistant#43]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option to chose Celcius or Fahrenheit

**Describe the solution you'd like**
checkbox to choose C or F

**Describe alternatives you've considered**

**Additional context**

Even if everything else is in Celcius in HA, i like to have my spa in fahrenheit

**Comment by gazoodle** [comment]
It ought to match the temperature unit on your spa, and I thought that it did but I checked this morning and despite setting my iOS app to Fahrenheit, the integration remains in Celcius ... I'll get it fixed.

**Comment by gazoodle** [comment]
Ok, so after some R&D, this is by design in HA. There is a global control for unit settings in the Basic/General settings page. So, whatever I return from the integration gets converted by HA to the UI requirement.

However, there is a way to customize the UI in the YAML configuration file, but for some reason I can't change the unit of measurement despite if being documented at https://www.home-assistant.io/docs/configuration/customizing-devices/

I can however change the icon of the climate control, something for the core team to address perhaps.
